hijbullah = "A student of IUBAT"
print(len(hijbullah))
print(hijbullah.upper())
x = hijbullah.lower()
print(x)
print(x.find("u"))
y = hijbullah.upper()
print(y.replace("IUBAT","BRAC"))
z= y.replace("IUBAT","BRAC")
print("BRAC" in z )
print(z.title())